name: cargo-semver-checks

permissions: read-all

on:
  pull_request: { paths: ['**/Cargo.toml'] }
  workflow_dispatch:
jobs:
  semver-checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.1
      - uses: obi1kenobi/cargo-semver-checks-action@v2
