name: CI

permissions: read-all

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v6
        with:
          rust-version: stable
      - run: cargo test --all-features --workspace
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Run coverage
        run: cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info
      - name: Check coverage threshold
        run: cargo llvm-cov report --fail-under-lines 70
